var obj={
    _readableState:
         {
        objectMode: false,
            highWaterMark: 16384,
            buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: true,
            endEmitted: true,
            reading: false,
            sync: false,
            needReadable: false,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            destroyed: false,
            defaultEncoding: 'utf8',
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null },
    readable: false,
        domain: null,
        _events: {},
    _eventsCount: 0,
        _maxListeners: undefined,
        socket:
    Socket {
        connecting: false,
            _hadError: false,
            _handle:
        TCP {
            reading: true,
                owner: [Circular],
                onread: [Function: onread],
            onconnection: null,
                writeQueueSize: 0,
                _consumed: true },
        _parent: null,
            _host: null,
            _readableState:
        ReadableState {
            objectMode: false,
                highWaterMark: 16384,
                buffer: [Object],
                length: 0,
                pipes: null,
                pipesCount: 0,
                flowing: true,
                ended: false,
                endEmitted: false,
                reading: true,
                sync: false,
                needReadable: true,
                emittedReadable: false,
                readableListening: false,
                resumeScheduled: false,
                destroyed: false,
                defaultEncoding: 'utf8',
                awaitDrain: 0,
                readingMore: false,
                decoder: null,
                encoding: null },
        readable: true,
            domain: null,
            _events:
        { end: [Array],
            finish: [Function: onSocketFinish],
            _socketEnd: [Function: onSocketEnd],
            drain: [Array],
                timeout: [Function: socketOnTimeout],
            data: [Function: bound socketOnData],
            error: [Array],
                close: [Array],
            resume: [Function: onSocketResume],
            pause: [Function: onSocketPause] },
        _eventsCount: 10,
            _maxListeners: undefined,
            _writableState:
        WritableState {
            objectMode: false,
                highWaterMark: 16384,
                finalCalled: false,
                needDrain: false,
                ending: false,
                ended: false,
                finished: false,
                destroyed: false,
                decodeStrings: false,
                defaultEncoding: 'utf8',
                length: 0,
                writing: false,
                corked: 0,
                sync: true,
                bufferProcessing: false,
                onwrite: [Function: bound onwrite],
            writecb: null,
                writelen: 0,
                bufferedRequest: null,
                lastBufferedRequest: null,
                pendingcb: 0,
                prefinished: false,
                errorEmitted: false,
                bufferedRequestCount: 0,
                corkedRequestsFree: [Object] },
        writable: true,
            allowHalfOpen: true,
            _bytesDispatched: 0,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server:
        Server {
            domain: null,
                _events: [Object],
                _eventsCount: 4,
                _maxListeners: undefined,
                _connections: 3,
                _handle: [Object],
                _usingSlaves: false,
                _slaves: [],
                _unref: false,
                allowHalfOpen: true,
                pauseOnConnect: false,
                httpAllowHalfOpen: false,
                timeout: 120000,
                keepAliveTimeout: 5000,
                _pendingResponseData: 0,
                maxHeadersCount: null,
                _connectionKey: '6::::3001',
                [Symbol(asyncId)]: 6 },
        _server:
            Server {
            domain: null,
                _events: [Object],
                _eventsCount: 4,
                _maxListeners: undefined,
                _connections: 3,
                _handle: [Object],
                _usingSlaves: false,
                _slaves: [],
                _unref: false,
                allowHalfOpen: true,
                pauseOnConnect: false,
                httpAllowHalfOpen: false,
                timeout: 120000,
                keepAliveTimeout: 5000,
                _pendingResponseData: 0,
                maxHeadersCount: null,
                _connectionKey: '6::::3001',
                [Symbol(asyncId)]: 6 },
        _idleTimeout: 120000,
            _idleNext:
        Socket {
            connecting: false,
                _hadError: false,
                _handle: [Object],
                _parent: null,
                _host: null,
                _readableState: [Object],
                readable: true,
                domain: null,
                _events: [Object],
                _eventsCount: 10,
                _maxListeners: undefined,
                _writableState: [Object],
                writable: true,
                allowHalfOpen: true,
                _bytesDispatched: 0,
                _sockname: null,
                _pendingData: null,
                _pendingEncoding: '',
                server: [Object],
                _server: [Object],
                _idleTimeout: 120000,
                _idleNext: [Object],
                _idlePrev: [Circular],
                _idleStart: 1550,
                _destroyed: false,
                parser: [Object],
                on: [Function: socketOnWrap],
            _paused: false,
                read: [Function],
                _consuming: true,
                _httpMessage: [Object],
                _peername: [Object],
                [Symbol(asyncId)]: 17,
                [Symbol(bytesRead)]: 0,
                [Symbol(asyncId)]: 18,
                [Symbol(triggerAsyncId)]: 17 },
        _idlePrev:
            TimersList {
            _idleNext: [Circular],
                _idlePrev: [Object],
                _timer: [Object],
                _unrefed: true,
                msecs: 120000,
                nextTick: false },
        _idleStart: 1569,
            _destroyed: false,
            parser:
        HTTPParser {
            '0': [Function: parserOnHeaders],
            '1': [Function: parserOnHeadersComplete],
            '2': [Function: parserOnBody],
            '3': [Function: parserOnMessageComplete],
            '4': [Function: bound onParserExecute],
            _headers: [],
                _url: '',
                _consumed: true,
                socket: [Circular],
                incoming: [Circular],
                outgoing: null,
                maxHeaderPairs: 2000,
                onIncoming: [Function: bound parserOnIncoming] },
        on: [Function: socketOnWrap],
        _paused: false,
            read: [Function],
            _consuming: true,
            _httpMessage:
        ServerResponse {
            domain: null,
                _events: [Object],
                _eventsCount: 2,
                _maxListeners: undefined,
                output: [],
                outputEncodings: [],
                outputCallbacks: [],
                outputSize: 0,
                writable: true,
                _last: false,
                upgrading: false,
                chunkedEncoding: false,
                shouldKeepAlive: false,
                useChunkedEncodingByDefault: true,
                sendDate: true,
                _removedConnection: false,
                _removedContLen: false,
                _removedTE: false,
                _contentLength: null,
                _hasBody: true,
                _trailer: '',
                finished: false,
                _headerSent: false,
                socket: [Circular],
                connection: [Circular],
                _header: null,
                _onPendingData: [Function: bound updateOutgoingData],
            _sent100: false,
                _expect_continue: false,
                statusCode: 404,
                __onFinished: [Object],
                [Symbol(outHeadersKey)]: null },
        _peername: { address: '::ffff:127.0.0.1', family: 'IPv6', port: 58235 },
        [Symbol(asyncId)]: 22,
            [Symbol(bytesRead)]: 0,
            [Symbol(asyncId)]: 23,
            [Symbol(triggerAsyncId)]: 22 },
    connection:
        Socket {
        connecting: false,
            _hadError: false,
            _handle:
        TCP {
            reading: true,
                owner: [Circular],
                onread: [Function: onread],
            onconnection: null,
                writeQueueSize: 0,
                _consumed: true },
        _parent: null,
            _host: null,
            _readableState:
        ReadableState {
            objectMode: false,
                highWaterMark: 16384,
                buffer: [Object],
                length: 0,
                pipes: null,
                pipesCount: 0,
                flowing: true,
                ended: false,
                endEmitted: false,
                reading: true,
                sync: false,
                needReadable: true,
                emittedReadable: false,
                readableListening: false,
                resumeScheduled: false,
                destroyed: false,
                defaultEncoding: 'utf8',
                awaitDrain: 0,
                readingMore: false,
                decoder: null,
                encoding: null },
        readable: true,
            domain: null,
            _events:
        { end: [Array],
            finish: [Function: onSocketFinish],
            _socketEnd: [Function: onSocketEnd],
            drain: [Array],
                timeout: [Function: socketOnTimeout],
            data: [Function: bound socketOnData],
            error: [Array],
                close: [Array],
            resume: [Function: onSocketResume],
            pause: [Function: onSocketPause] },
        _eventsCount: 10,
            _maxListeners: undefined,
            _writableState:
        WritableState {
            objectMode: false,
                highWaterMark: 16384,
                finalCalled: false,
                needDrain: false,
                ending: false,
                ended: false,
                finished: false,
                destroyed: false,
                decodeStrings: false,
                defaultEncoding: 'utf8',
                length: 0,
                writing: false,
                corked: 0,
                sync: true,
                bufferProcessing: false,
                onwrite: [Function: bound onwrite],
            writecb: null,
                writelen: 0,
                bufferedRequest: null,
                lastBufferedRequest: null,
                pendingcb: 0,
                prefinished: false,
                errorEmitted: false,
                bufferedRequestCount: 0,
                corkedRequestsFree: [Object] },
        writable: true,
            allowHalfOpen: true,
            _bytesDispatched: 0,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server:
        Server {
            domain: null,
                _events: [Object],
                _eventsCount: 4,
                _maxListeners: undefined,
                _connections: 3,
                _handle: [Object],
                _usingSlaves: false,
                _slaves: [],
                _unref: false,
                allowHalfOpen: true,
                pauseOnConnect: false,
                httpAllowHalfOpen: false,
                timeout: 120000,
                keepAliveTimeout: 5000,
                _pendingResponseData: 0,
                maxHeadersCount: null,
                _connectionKey: '6::::3001',
                [Symbol(asyncId)]: 6 },
        _server:
            Server {
            domain: null,
                _events: [Object],
                _eventsCount: 4,
                _maxListeners: undefined,
                _connections: 3,
                _handle: [Object],
                _usingSlaves: false,
                _slaves: [],
                _unref: false,
                allowHalfOpen: true,
                pauseOnConnect: false,
                httpAllowHalfOpen: false,
                timeout: 120000,
                keepAliveTimeout: 5000,
                _pendingResponseData: 0,
                maxHeadersCount: null,
                _connectionKey: '6::::3001',
                [Symbol(asyncId)]: 6 },
        _idleTimeout: 120000,
            _idleNext:
        Socket {
            connecting: false,
                _hadError: false,
                _handle: [Object],
                _parent: null,
                _host: null,
                _readableState: [Object],
                readable: true,
                domain: null,
                _events: [Object],
                _eventsCount: 10,
                _maxListeners: undefined,
                _writableState: [Object],
                writable: true,
                allowHalfOpen: true,
                _bytesDispatched: 0,
                _sockname: null,
                _pendingData: null,
                _pendingEncoding: '',
                server: [Object],
                _server: [Object],
                _idleTimeout: 120000,
                _idleNext: [Object],
                _idlePrev: [Circular],
                _idleStart: 1550,
                _destroyed: false,
                parser: [Object],
                on: [Function: socketOnWrap],
            _paused: false,
                read: [Function],
                _consuming: true,
                _httpMessage: [Object],
                _peername: [Object],
                [Symbol(asyncId)]: 17,
                [Symbol(bytesRead)]: 0,
                [Symbol(asyncId)]: 18,
                [Symbol(triggerAsyncId)]: 17 },
        _idlePrev:
            TimersList {
            _idleNext: [Circular],
                _idlePrev: [Object],
                _timer: [Object],
                _unrefed: true,
                msecs: 120000,
                nextTick: false },
        _idleStart: 1569,
            _destroyed: false,
            parser:
        HTTPParser {
            '0': [Function: parserOnHeaders],
            '1': [Function: parserOnHeadersComplete],
            '2': [Function: parserOnBody],
            '3': [Function: parserOnMessageComplete],
            '4': [Function: bound onParserExecute],
            _headers: [],
                _url: '',
                _consumed: true,
                socket: [Circular],
                incoming: [Circular],
                outgoing: null,
                maxHeaderPairs: 2000,
                onIncoming: [Function: bound parserOnIncoming] },
        on: [Function: socketOnWrap],
        _paused: false,
            read: [Function],
            _consuming: true,
            _httpMessage:
        ServerResponse {
            domain: null,
                _events: [Object],
                _eventsCount: 2,
                _maxListeners: undefined,
                output: [],
                outputEncodings: [],
                outputCallbacks: [],
                outputSize: 0,
                writable: true,
                _last: false,
                upgrading: false,
                chunkedEncoding: false,
                shouldKeepAlive: false,
                useChunkedEncodingByDefault: true,
                sendDate: true,
                _removedConnection: false,
                _removedContLen: false,
                _removedTE: false,
                _contentLength: null,
                _hasBody: true,
                _trailer: '',
                finished: false,
                _headerSent: false,
                socket: [Circular],
                connection: [Circular],
                _header: null,
                _onPendingData: [Function: bound updateOutgoingData],
            _sent100: false,
                _expect_continue: false,
                statusCode: 404,
                __onFinished: [Object],
                [Symbol(outHeadersKey)]: null },
        _peername: { address: '::ffff:127.0.0.1', family: 'IPv6', port: 58235 },
        [Symbol(asyncId)]: 22,
            [Symbol(bytesRead)]: 0,
            [Symbol(asyncId)]: 23,
            [Symbol(triggerAsyncId)]: 22 },
    httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers:
    { cookie: 'Webstorm-19161aa4=32b87e49-93e7-4414-a0a7-561463928986; Phpstorm-4f3d12e9=39369a9a-2c5d-4ccc-8bf3-1708340aad1b; _ga=GA1.1.1127347042.1522916362; PHPSESSID=j3m9782keds38rn5mteejmkke3',
        'accept-language': 'zh-CN,zh;q=0.9',
        'accept-encoding': 'gzip, deflate, br',
        referer: 'http://localhost:3000/',
        'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36',
        'x-requested-with': 'XMLHttpRequest',
        origin: 'http://localhost:3000',
        accept: '*/*',
        'content-length': '7',
        connection: 'close',
        host: 'localhost:3001' },
    rawHeaders:
        [ 'cookie',
            'Webstorm-19161aa4=32b87e49-93e7-4414-a0a7-561463928986; Phpstorm-4f3d12e9=39369a9a-2c5d-4ccc-8bf3-1708340aad1b; _ga=GA1.1.1127347042.1522916362; PHPSESSID=j3m9782keds38rn5mteejmkke3',
            'accept-language',
            'zh-CN,zh;q=0.9',
            'accept-encoding',
            'gzip, deflate, br',
            'referer',
            'http://localhost:3000/',
            'content-type',
            'application/x-www-form-urlencoded; charset=UTF-8',
            'user-agent',
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36',
            'x-requested-with',
            'XMLHttpRequest',
            'origin',
            'http://localhost:3000',
            'accept',
            '*/*',
            'content-length',
            '7',
            'connection',
            'close',
            'host',
            'localhost:3001' ],
            trailers: {},
    rawTrailers: [],
        upgrade: false,
        url: '/mysqlpost',
        method: 'POST',
        statusCode: null,
        statusMessage: null,
        client:
    Socket {
        connecting: false,
            _hadError: false,
            _handle:
        TCP {
            reading: true,
                owner: [Circular],
                onread: [Function: onread],
            onconnection: null,
                writeQueueSize: 0,
                _consumed: true },
        _parent: null,
            _host: null,
            _readableState:
        ReadableState {
            objectMode: false,
                highWaterMark: 16384,
                buffer: [Object],
                length: 0,
                pipes: null,
                pipesCount: 0,
                flowing: true,
                ended: false,
                endEmitted: false,
                reading: true,
                sync: false,
                needReadable: true,
                emittedReadable: false,
                readableListening: false,
                resumeScheduled: false,
                destroyed: false,
                defaultEncoding: 'utf8',
                awaitDrain: 0,
                readingMore: false,
                decoder: null,
                encoding: null },
        readable: true,
            domain: null,
            _events:
        { end: [Array],
            finish: [Function: onSocketFinish],
            _socketEnd: [Function: onSocketEnd],
            drain: [Array],
                timeout: [Function: socketOnTimeout],
            data: [Function: bound socketOnData],
            error: [Array],
                close: [Array],
            resume: [Function: onSocketResume],
            pause: [Function: onSocketPause] },
        _eventsCount: 10,
            _maxListeners: undefined,
            _writableState:
        WritableState {
            objectMode: false,
                highWaterMark: 16384,
                finalCalled: false,
                needDrain: false,
                ending: false,
                ended: false,
                finished: false,
                destroyed: false,
                decodeStrings: false,
                defaultEncoding: 'utf8',
                length: 0,
                writing: false,
                corked: 0,
                sync: true,
                bufferProcessing: false,
                onwrite: [Function: bound onwrite],
            writecb: null,
                writelen: 0,
                bufferedRequest: null,
                lastBufferedRequest: null,
                pendingcb: 0,
                prefinished: false,
                errorEmitted: false,
                bufferedRequestCount: 0,
                corkedRequestsFree: [Object] },
        writable: true,
            allowHalfOpen: true,
            _bytesDispatched: 0,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server:
        Server {
            domain: null,
                _events: [Object],
                _eventsCount: 4,
                _maxListeners: undefined,
                _connections: 3,
                _handle: [Object],
                _usingSlaves: false,
                _slaves: [],
                _unref: false,
                allowHalfOpen: true,
                pauseOnConnect: false,
                httpAllowHalfOpen: false,
                timeout: 120000,
                keepAliveTimeout: 5000,
                _pendingResponseData: 0,
                maxHeadersCount: null,
                _connectionKey: '6::::3001',
                [Symbol(asyncId)]: 6 },
        _server:
            Server {
            domain: null,
                _events: [Object],
                _eventsCount: 4,
                _maxListeners: undefined,
                _connections: 3,
                _handle: [Object],
                _usingSlaves: false,
                _slaves: [],
                _unref: false,
                allowHalfOpen: true,
                pauseOnConnect: false,
                httpAllowHalfOpen: false,
                timeout: 120000,
                keepAliveTimeout: 5000,
                _pendingResponseData: 0,
                maxHeadersCount: null,
                _connectionKey: '6::::3001',
                [Symbol(asyncId)]: 6 },
        _idleTimeout: 120000,
            _idleNext:
        Socket {
            connecting: false,
                _hadError: false,
                _handle: [Object],
                _parent: null,
                _host: null,
                _readableState: [Object],
                readable: true,
                domain: null,
                _events: [Object],
                _eventsCount: 10,
                _maxListeners: undefined,
                _writableState: [Object],
                writable: true,
                allowHalfOpen: true,
                _bytesDispatched: 0,
                _sockname: null,
                _pendingData: null,
                _pendingEncoding: '',
                server: [Object],
                _server: [Object],
                _idleTimeout: 120000,
                _idleNext: [Object],
                _idlePrev: [Circular],
                _idleStart: 1550,
                _destroyed: false,
                parser: [Object],
                on: [Function: socketOnWrap],
            _paused: false,
                read: [Function],
                _consuming: true,
                _httpMessage: [Object],
                _peername: [Object],
                [Symbol(asyncId)]: 17,
                [Symbol(bytesRead)]: 0,
                [Symbol(asyncId)]: 18,
                [Symbol(triggerAsyncId)]: 17 },
        _idlePrev:
            TimersList {
            _idleNext: [Circular],
                _idlePrev: [Object],
                _timer: [Object],
                _unrefed: true,
                msecs: 120000,
                nextTick: false },
        _idleStart: 1569,
            _destroyed: false,
            parser:
        HTTPParser {
            '0': [Function: parserOnHeaders],
            '1': [Function: parserOnHeadersComplete],
            '2': [Function: parserOnBody],
            '3': [Function: parserOnMessageComplete],
            '4': [Function: bound onParserExecute],
            _headers: [],
                _url: '',
                _consumed: true,
                socket: [Circular],
                incoming: [Circular],
                outgoing: null,
                maxHeaderPairs: 2000,
                onIncoming: [Function: bound parserOnIncoming] },
        on: [Function: socketOnWrap],
        _paused: false,
            read: [Function],
            _consuming: true,
            _httpMessage:
        ServerResponse {
            domain: null,
                _events: [Object],
                _eventsCount: 2,
                _maxListeners: undefined,
                output: [],
                outputEncodings: [],
                outputCallbacks: [],
                outputSize: 0,
                writable: true,
                _last: false,
                upgrading: false,
                chunkedEncoding: false,
                shouldKeepAlive: false,
                useChunkedEncodingByDefault: true,
                sendDate: true,
                _removedConnection: false,
                _removedContLen: false,
                _removedTE: false,
                _contentLength: null,
                _hasBody: true,
                _trailer: '',
                finished: false,
                _headerSent: false,
                socket: [Circular],
                connection: [Circular],
                _header: null,
                _onPendingData: [Function: bound updateOutgoingData],
            _sent100: false,
                _expect_continue: false,
                statusCode: 404,
                __onFinished: [Object],
                [Symbol(outHeadersKey)]: null },
        _peername: { address: '::ffff:127.0.0.1', family: 'IPv6', port: 58235 },
        [Symbol(asyncId)]: 22,
            [Symbol(bytesRead)]: 0,
            [Symbol(asyncId)]: 23,
            [Symbol(triggerAsyncId)]: 22 },
    _consuming: true,
        _dumped: false,
        read: [Function],
        _parsedUrl:
    Url {
        protocol: null,
            slashes: null,
            auth: null,
            host: null,
            port: null,
            hostname: null,
            hash: null,
            search: null,
            query: null,
            pathname: '/mysqlpost',
            path: '/mysqlpost',
            href: '/mysqlpost',
            _raw: '/mysqlpost' } }
